import type { ReviewIssue, ReviewResponse } from "@/lib/schemas/review";
import { GitHubIntegrationError } from "@/lib/github/errors";
import type { GitHubClient } from "@/lib/github/types";

export const REVIEWPILOT_COMMENT_MARKER = "<!-- reviewpilot-ai -->";
export const MAX_COMMENT_CHARS = 60_000;

const riskLabels = { low: "Low", medium: "Medium", high: "High" } as const;
const recommendationLabels = {
	approve: "Approve",
	needs_changes: "Needs changes",
	reject: "Reject",
} as const;

export function formatReviewComment(
	review: ReviewResponse,
	maxChars = MAX_COMMENT_CHARS,
) {
	const sections = [
		REVIEWPILOT_COMMENT_MARKER,
		"",
		"## ReviewPilot AI Report",
		"",
		`**Overall risk:** ${riskLabels[review.overallRisk]}  `,
		`**Risk score:** ${review.riskScore}/100  `,
		`**Confidence:** ${Math.round(review.confidence * 100)}%  `,
		`**Recommendation:** ${recommendationLabels[review.mergeRecommendation]}`,
		"",
		"### Summary",
		"",
		escapeMarkdown(review.summary),
		"",
		formatIssues("Possible bugs", review.possibleBugs),
		"",
		formatIssues("Refactoring suggestions", review.refactoringSuggestions),
		"",
		"### Suggested tests",
		"",
		review.testSuggestions.length
			? review.testSuggestions
					.map((suggestion) => `- ${escapeMarkdown(suggestion)}`)
					.join("\n")
			: "_No specific tests were suggested._",
		"",
		"---",
		"",
		"Generated by [ReviewPilot AI](https://github.com/JohnImril/reviewpilot-ai). This automated review may miss issues and does not replace human review.",
	].join("\n");

	return limitComment(sections, maxChars);
}

export function formatReviewNotice(
	message: string,
	maxChars = MAX_COMMENT_CHARS,
) {
	return limitComment(
		[
			REVIEWPILOT_COMMENT_MARKER,
			"",
			"## ReviewPilot AI Report",
			"",
			escapeMarkdown(message),
			"",
			"---",
			"",
			"Generated by [ReviewPilot AI](https://github.com/JohnImril/reviewpilot-ai). No completeness guarantee is made.",
		].join("\n"),
		maxChars,
	);
}

export async function upsertReviewComment(input: {
	client: GitHubClient;
	appId: number;
	owner: string;
	repo: string;
	pullNumber: number;
	body: string;
}) {
	const comments = await input.client.listIssueComments({
		owner: input.owner,
		repo: input.repo,
		issueNumber: input.pullNumber,
	});
	const existing = comments.find(
		(comment) =>
			comment.body?.includes(REVIEWPILOT_COMMENT_MARKER) &&
			comment.performed_via_github_app?.id === input.appId,
	);

	try {
		if (existing) {
			await input.client.updateIssueComment({
				owner: input.owner,
				repo: input.repo,
				commentId: existing.id,
				body: input.body,
			});
			return "updated" as const;
		}
		await input.client.createIssueComment({
			owner: input.owner,
			repo: input.repo,
			issueNumber: input.pullNumber,
			body: input.body,
		});
		return "created" as const;
	} catch (error) {
		throw new GitHubIntegrationError(
			"comment_publication_error",
			"Unable to publish the ReviewPilot pull request comment.",
			502,
			{ cause: error },
		);
	}
}

function formatIssues(title: string, issues: ReviewIssue[]) {
	if (issues.length === 0) {
		return `### ${title}\n\n_None found by the configured provider._`;
	}
	return `### ${title}\n\n${issues.map(formatIssue).join("\n\n")}`;
}

function formatIssue(issue: ReviewIssue) {
	const location = issue.location
		? `${inlineCode(issue.location.filePath)}${
				issue.location.lineNumber ? `:${issue.location.lineNumber}` : ""
			}`
		: "Pull request level";
	return [
		`#### ${escapeMarkdown(issue.title)}`,
		`- Severity: ${riskLabels[issue.severity]}`,
		`- Location: ${location}`,
		`- Description: ${escapeMarkdown(issue.description)}`,
		`- Suggested fix: ${escapeMarkdown(issue.suggestedFix)}`,
	].join("\n");
}

export function escapeMarkdown(value: string) {
	return value
		.replace(/\\/g, "\\\\")
		.replace(/([`*_{}\[\]()<>#+\-.!|])/g, "\\$1")
		.replace(/\r?\n/g, "  \n");
}

function inlineCode(value: string) {
	return `\`${value.replace(/[`\r\n]/g, "'")}\``;
}

function limitComment(comment: string, maxChars: number) {
	if (comment.length <= maxChars) return comment;
	const suffix =
		"\n\n---\n\n_Report shortened to fit GitHub comment limits. ReviewPilot does not guarantee complete coverage._";
	return `${comment.slice(0, Math.max(REVIEWPILOT_COMMENT_MARKER.length, maxChars - suffix.length))}${suffix}`;
}
